version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x

  pre-build:
    commands:
      - cd cicd      # change directory
      - bash install-terraform.sh
      - bash configure-named-profile.sh
  build:
    commands:
      - bash apply-terraform.sh